server:
  port: 8089

spring:
  profiles:
    include: [center]
  ####### Redis Config #######
  redis:
    database: 5
    # Redis服务器地址
    host: 127.0.0.1
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:

  ####### redis缓存服务配置 #######
  session:
    store-type: redis